spring:
  application:
    name: my-langchain4j
  #连接数据库
  datasource:
    url: jdbc:mysql://localhost:3306/langchain4j
    username: root
    password: root


langchain4j:
  open-ai:
    chat-model:
      api-key: ${ApiKey}
      base-url: ${BaseUrl}
      model-name: ${ModelName}

      log-requests: true
      log-responses: true

  #阿里百炼平台
  community:
    dashscope:
      chat-model:
        api-key: ${ApiKey}
        base-url: ${BaseUrl}
        model-name: ${ModelName}
      streaming-chat-model:
        api-key: ${ApiKey}
        base-url: ${BaseUrl}
        model-name: ${ModelName}



